- name: 'Create script and configuration on teleport-server'
  hosts: 'teleport-server'
  gather_facts: true
  become: true

  pre_tasks:

    - name: 'Copy teleport-demo_ca.crt to node'
      ansible.builtin.copy:
        src: 'Teleport_demo_CA/teleport-demo_ca.crt'
        dest: '/etc/pki/trust/anchors/teleport-demo_ca.crt'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Install teleport-tctl package'
      ansible.builtin.package:
        name: 'teleport-tctl'
        state: 'installed'

  roles:
    - role: 'johanneskastl.configure_and_start_teleport'
      vars:
        cluster_name: 'teleport_with_vagrant_libvirt'
        enable_auth_service: true
        enable_proxy_service: true
        enable_ssh_service: true
        enable_windows_desktop_service: false
        enable_db_service: false
        enable_kubernetes_service: false
        enable_app_service: false
        auth_service_authentication:
          second_factor: 'off'
        auth_service_tokens:
          - '"node:very_insecure_token_that_should_not_be_used"'
        labels:
          env: 'example'
          type: 'server'
        commands:
          - name: 'hostname'
            command: '[hostname]'
            period: '1m0s'
          - name: 'operating_system'
            command: ["bash", "-c", "awk -F'=' '/^PRETTY/ {print $2}' /etc/os-release"]
            period: '30m'
