---
- name: 'Add home_ojkastl_buildservice_teleport repository containing teleport'
  hosts: 'teleport_servers,teleport_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'add_zypper_repository'
      vars:
        repository_name: 'home_ojkastl_buildservice_teleport'
        repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/teleport/openSUSE_Leap_{{ ansible_distribution_version }}"
        auto_import_keys: true
    - role: 'zypper_ref_accept_keys'
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'teleport'
          - 'teleport-tsh'
          - 'hostname'
    - role: 'minimal_bashrc'
      vars:
        additional_users: "{{ ansible_user }}"
    - role: 'create_a_vimrc'
      vars:
        additional_users: "{{ ansible_user }}"

- name: 'Create certificate for teleport-server'
  hosts: 'teleport-server'
  gather_facts: 'yes'
  become: 'true'
  roles:
    - role: 'selfsigned_demo_ca'
      vars:
        # Variables for the CA
        ca_key_file: 'teleport-demo_ca.key'
        ca_csr_file: 'teleport-demo_ca.csr'
        ca_crt_file: 'teleport-demo_ca.crt'
        ca_target_folder: 'Teleport_demo_CA/'
        ca_key_passphrase: 'somethingtotallysecret'
        # Variables for the host
        certs_file_user: 'root'
        certs_file_group: 'root'
        create_certs_for_hosts: 'true'
        use_IP_address_only: 'true'

- name: 'Include teleport-server-configuration playbook'
  import_playbook: playbook-teleport-server-configuration.yml
  when: 'inventory_hostname == "teleport-server"'

- name: 'Include teleport-nodes-configuration playbook'
  import_playbook: playbook-teleport-nodes-configuration.yml
  when: 'inventory_hostname != "teleport-server"'
