---

#
# bootstrap python3.11
#

- name: 'Run playbook-all_nodes-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python.yml

#
# general configuration
#

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

#
# Teleport
#

- name: 'Add home_ojkastl_buildservice_teleport repository containing teleport'
  hosts: 'teleport_servers,teleport_nodes'
  gather_facts: 'yes'
  become: 'true'

  roles:
    - role: 'add_zypper_repository'
      vars:
        repository_name: 'home_ojkastl_buildservice_teleport'
        repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/teleport/openSUSE_Leap_{{ ansible_distribution_version }}"
        auto_import_keys: true
    - role: 'zypper_ref_accept_keys'
    - role: 'install_one_or_more_packages'
      vars:
        packages_to_be_installed:
          - 'teleport'
          - 'teleport-tsh'
          - 'hostname'

- name: 'Include playbook-teleport-server-generate_certificate.yml'
  import_playbook: playbook-teleport-server-generate_certificate.yml
  when: 'inventory_hostname == "teleport-server"'

- name: 'Include teleport-server-configuration playbook'
  import_playbook: playbook-teleport-server-configuration.yml
  when: 'inventory_hostname == "teleport-server"'

- name: 'Include teleport-nodes-configuration playbook'
  import_playbook: playbook-teleport-nodes-configuration.yml
  when: 'inventory_hostname != "teleport-server"'
