---
- name: 'Add the Branch_devel_kubic zypper repository'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:

    - role: 'johanneskastl.add_zypper_repository'
      repository_name: 'home-ojkastl_buildservice-Branch_devel_kubic'
      repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/Branch_devel_kubic/openSUSE_Tumbleweed/"
      auto_import_keys: '1'
      when:
        - ansible_distribution == "openSUSE Tumbleweed"

    - role: 'johanneskastl.add_zypper_repository'
      repository_name: 'home:ojkastl_buildservice:Branch_devel_kubic'
      repository_baseurl: "https://download.opensuse.org/repositories/home:/ojkastl_buildservice:/Branch_devel_kubic/{{ ansible_distribution_version }}/"
      auto_import_keys: '1'
      when:
        - ansible_distribution == 'openSUSE Leap' or ansible_distribution == 'SLES'
