---

#
# bootstrap python3.11
#

- name: 'Run playbook-all_nodes-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-bootstrap_python.yml

#
# general configuration
#

- name: 'Run playbook-all_nodes-create_a_vimrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-create_a_vimrc.yml

- name: 'Run playbook-all_nodes-install_tmux.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_tmux.yml

- name: 'Run playbook-all_nodes-minimal_tmux_configuration.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_tmux_configuration.yml

- name: 'Run playbook-all_nodes-minimal_bashrc.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-minimal_bashrc.yml

#
# Teleport
#

- name: 'Run playbook-all_nodes-add_Branch_devel_kubic_repo.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-add_Branch_devel_kubic_repo.yml

- name: 'Run playbook-all_nodes-install_teleport.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_teleport.yml

- name: 'Run playbook-teleport_server-generate_certificate.yml'
  import_playbook: playbook-teleport_server-generate_certificate.yml
  when: 'inventory_hostname == "teleport-server"'

- name: 'Run playbook-teleport_server-configuration.yml'
  import_playbook: playbook-teleport_server-configuration.yml

- name: 'Run playbook-teleport_nodes-configuration.yml'
  import_playbook: playbook-teleport_nodes-configuration.yml
