---

- name: 'Create CA on Ansible control host'
  hosts: 'teleport-server'
  gather_facts: true
  become: false

  roles:

    - role: 'johanneskastl.selfsigned_demo_ca'
      delegate_to: 'localhost'
      vars:
        generate_demo_ca: 'true'
        create_certs_for_hosts: 'false'
        # Variables for the CA
        ca_key_file: 'teleport-demo_ca.key'
        ca_csr_file: 'teleport-demo_ca.csr'
        ca_crt_file: 'teleport-demo_ca.crt'
        ca_target_folder: 'Teleport_demo_CA/'
        ca_key_passphrase: 'somethingtotallysecret'
