- name: 'Create script and configuration on teleport-server'
  hosts: 'teleport-server'
  gather_facts: 'yes'
  become: 'true'

  tasks:

    - name: 'Copy teleport-demo_ca.crt to node'
      copy:
        src: 'Teleport_demo_CA/teleport-demo_ca.crt'
        dest: '/etc/pki/trust/anchors/teleport-demo_ca.crt'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Install teleport-tctl package'
      package:
        name: 'teleport-tctl'
        state: 'installed'

    - name: 'create directory /var/lib/teleport/'
      file:
        path: '/var/lib/teleport/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0750'

    - name: 'Create /etc/teleport.yaml'
      template:
        src: 'teleport-server.yaml.j2'
        dest: '/etc/teleport.yaml'
        owner: 'root'
        group: 'root'
        mode: '0600'
      notify:
        - 'Restart the teleport service'

    - name: 'Start the teleport service'
      service:
        name: 'teleport'
        state: 'started'
        enabled: 'true'

  handlers:

    - name: 'Restart the teleport service'
      service:
        name: 'teleport'
        state: 'restarted'

